import React from "react";
import Head from "next/head";
import styles from "./Layout.module.css";
import Header from "./header";
import Sidebar from "./sidebar";
import { useMediaQuery } from "../../hooks";

const Layout = ({ children }) => {
  const isMobile = useMediaQuery("(max-width: 768px)");

  return (
    <>
      <Head>
        <title>E-Bookstore</title>
        <meta name="description" content="Generated by Gizem Candemir" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={styles.container}>
        <Header />
        <div className={styles.content}>
          {!isMobile && <Sidebar />}
          <main className={styles.main}>{children}</main>
        </div>
      </div>
    </>
  );
};

export default Layout;
